// <auto-generated />
using System;
using AltaGasTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AltaGasTest.Data.Migrations.Initials
{
    [DbContext(typeof(AltaGasTestDbContext))]
    [Migration("20251213143534_InitialSetUp")]
    partial class InitialSetUp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AltaGasTest.Data.Entities.CanadianCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CanadianCities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityName = "Vancouver",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 2,
                            CityName = "Victoria",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 3,
                            CityName = "Kelowna",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 4,
                            CityName = "Kamloops",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 5,
                            CityName = "Prince George",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 6,
                            CityName = "Calgary",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 7,
                            CityName = "Edmonton",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 8,
                            CityName = "Lethbridge",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 9,
                            CityName = "Red Deer",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 10,
                            CityName = "Fort McMurray",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 11,
                            CityName = "Regina",
                            TimeZone = "Canada Central Standard Time"
                        },
                        new
                        {
                            Id = 12,
                            CityName = "Saskatoon",
                            TimeZone = "Canada Central Standard Time"
                        },
                        new
                        {
                            Id = 13,
                            CityName = "Moose Jaw",
                            TimeZone = "Canada Central Standard Time"
                        },
                        new
                        {
                            Id = 14,
                            CityName = "Brandon",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 15,
                            CityName = "Winnipeg",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 16,
                            CityName = "Thunder Bay",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 17,
                            CityName = "Sault Ste. Marie",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 18,
                            CityName = "Sudbury",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 19,
                            CityName = "North Bay",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 20,
                            CityName = "Barrie",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 21,
                            CityName = "Toronto",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 22,
                            CityName = "Mississauga",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 23,
                            CityName = "Hamilton",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 24,
                            CityName = "London",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 25,
                            CityName = "Kitchener",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 26,
                            CityName = "Windsor",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 27,
                            CityName = "St. Catharines",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 28,
                            CityName = "Oshawa",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 29,
                            CityName = "Kingston",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 30,
                            CityName = "Ottawa",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 31,
                            CityName = "Gatineau",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 32,
                            CityName = "Montreal",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 33,
                            CityName = "Quebec City",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 34,
                            CityName = "Sherbrooke",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 35,
                            CityName = "Trois-RiviÃ¨res",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 36,
                            CityName = "Saguenay",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 37,
                            CityName = "Rimouski",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 38,
                            CityName = "Edmundston",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 39,
                            CityName = "Fredericton",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 40,
                            CityName = "Moncton",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 41,
                            CityName = "Saint John",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 42,
                            CityName = "Bathurst",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 43,
                            CityName = "Charlottetown",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 44,
                            CityName = "Summerside",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 45,
                            CityName = "Sydney",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 46,
                            CityName = "Truro",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 47,
                            CityName = "New Glasgow",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 48,
                            CityName = "Dartmouth",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 49,
                            CityName = "Halifax",
                            TimeZone = "Atlantic Standard Time"
                        });
                });

            modelBuilder.Entity("AltaGasTest.Data.Entities.EquipmentEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("EquipmentEvents");
                });

            modelBuilder.Entity("AltaGasTest.Data.Entities.EventCodeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("EventCodeDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventCode = "W",
                            EventDescription = "Released",
                            LongDescription = "Railcar equipment is released from origin"
                        },
                        new
                        {
                            Id = 2,
                            EventCode = "A",
                            EventDescription = "Arrived",
                            LongDescription = "Railcar equipment arrives at a city on route"
                        },
                        new
                        {
                            Id = 3,
                            EventCode = "D",
                            EventDescription = "Departed",
                            LongDescription = "Railcar equipment departs from a city on route"
                        },
                        new
                        {
                            Id = 4,
                            EventCode = "Z",
                            EventDescription = "Placed",
                            LongDescription = "Railcar equipment is placed at destination"
                        });
                });

            modelBuilder.Entity("AltaGasTest.Data.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DestinationCityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginCityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalTripHours")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("OriginCityId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("AltaGasTest.Data.Entities.EquipmentEvent", b =>
                {
                    b.HasOne("AltaGasTest.Data.Entities.CanadianCity", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("AltaGasTest.Data.Entities.Trip", b =>
                {
                    b.HasOne("AltaGasTest.Data.Entities.CanadianCity", "DestinationCity")
                        .WithMany()
                        .HasForeignKey("DestinationCityId");

                    b.HasOne("AltaGasTest.Data.Entities.CanadianCity", "OriginCity")
                        .WithMany()
                        .HasForeignKey("OriginCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DestinationCity");

                    b.Navigation("OriginCity");
                });
#pragma warning restore 612, 618
        }
    }
}
